# Generated by Django 2.2.6 on 2019-10-25 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detektor_suhu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='humadity',
            new_name='humidity',
        ),
    ]
